language: python
matrix:
  include:
    - name: "Python 3.6 on Windows"
      os: windows
      language:  shell
      before_install:
        - choco install python --version 3.6
        - python --version
        - python3 -m pip3 install --upgrade pip
        - pip3 install -r requirements.txt
        - python3 setup.py -q install
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
      script: travis_wait 35 python3 -m unittest discover
    - name: "Python 3.6.5 on macOS 10.13"
      os: osx
      osx_image: xcode9.4  # Python 3.6.5 running on macOS 10.13
      language: shell  # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip install -r requirements.txt
        - python3 setup.py -q install
      script: travis_wait 35 python3 -m unittest discover
sudo: false
cache: pip
